import { z } from "zod";

// Enums matching the database definitions
export const FormStatusEnum = z.enum(["DRAFT", "PUBLISHED", "ARCHIVED"]);
export const VisibilityEnum = z.enum(["PUBLIC", "UNLISTED"]);

export const FormSchema = z
  .object({
    // ID is generated by the database; optional on input
    id: z.string().uuid().optional(),

    // Creator must be a valid UUID referencing a user
    creatorId: z.string().uuid(),

    // Basic metadata
    title: z.string().min(1).max(255),
    description: z.string().max(5000).optional(),
    shareId: z.string().min(1).max(255),
    slug: z.string().max(255).optional(),

    // Enum fields – strict validation against allowed values
    status: FormStatusEnum,
    visibility: VisibilityEnum,

    // Response handling flags
    acceptsResponses: z.boolean(),
    responseLimit: z.number().int().positive().optional(),
    expiresAt: z.coerce.date().optional(),

    // Optional password protection (hashed password stored)
    isPasswordProtected: z.boolean(),
    formPassword: z.string().optional(),

    // UI/UX customisation fields
    thankYouMessage: z.string().max(1000).optional(),
    theme: z.enum(["Naruto", "Death Note", "Attack On Titan"]).default("Naruto"),

    // Notification toggles
    notifyCreator: z.boolean(),
    notifyRespondent: z.boolean(),

    // Timestamps – set by the server, optional on input
    publishedAt: z.coerce.date().optional(),
    createdAt: z.coerce.date().optional(),
    updatedAt: z.coerce.date().optional(),
  })
  .strict();

// Export TypeScript type for convenience
export type FormInput = z.infer<typeof FormSchema>;
